apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql
  namespace: safety
data: 
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: mysql
      tier: db
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: hanvihanshith/mysql:v1
        imagePullPolicy: Always
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
       - name: mysql-config
         configMap:
          name: mysql

---
apiVersion: v1 
kind: Service
metadata: 
  name: mysql
  namespace: safety
spec:
  selector:
    project: safety
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 ## services port
      targetPort: 3306 ## container port