apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      serviceAccount: secret-mysql-reader
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id roboshop/dev/mysql_password --query 'SecretString' --output text | jq -r '.["mysql-password"]' > /tmp/mysql-root-password.txt
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp
      containers:
      - name: mysql
        image: joindevops/mysql:v2
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: mysql-secret
          mountPath: /tmp
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
        - name: mysql-secret
          emptyDir: {}